# -*- coding: utf-8 -*-
"""Assignment_setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s6eZDtvdDmBreauwrtMd80TXrDY7znJg
"""

import pandas as pd

import io

import requests

url = "https://raw.githubusercontent.com/swarj/MLAssignment1/main/Concrete_Data.xlsx%20-%20Sheet1.csv"

df = pd.read_csv(url)

#Y = df[['Concrete compressive strength(MPa, megapascals)']] #We want to be able to predict Y, the concrete strength

#X = df.drop(['Concrete compressive strength(MPa, megapascals)'], axis = 1) #X contains all the factors we want to predict Y

from sklearn.model_selection import train_test_split #using SKlearn function to split into training and testing

train, test = train_test_split(df, test_size = 0.8) #finished split, let's begin model construction

